# Generated by Django 5.1.4 on 2025-01-07 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_todolist_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="user",
        ),
    ]
